project:
  type: website

website:
  title: "Anabeth Radunz"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: "CV (Page)"
        href: cv.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/anabethradunz
      - icon: envelope
        href: mailto:anabethradunz@gmail.com

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
